import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { gql } from "@apollo/client";
import { client } from "../lib/apollo";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rethink Event</h1>
      </main>

      <div className="posts">
        {posts.map(({ title, uri }) => (
          <div key={uri} className="box">
            <a>{title}</a>
          </div>
        ))}
      </div>

      <footer className={styles.footer}>
        <p>
          Rethink Event +45 22 50 77 42 info@rethinkevent.dk CVR-NR: 35124616
          Vaerksted Karupvej 6 8000 Aarhus C
        </p>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const result = await client.query({
    query: gql`
      query getPosts {
        posts {
          nodes {
            title
            slug
            date
          }
        }
      }
    `,
  });

  return {
    props: {
      posts: result.data.posts.nodes,
    },
  };
}
